### ISSUE TITLE
Document packaging steps

### ISSUE THREAD

**Issue by vincentjames501** [Gonzih/cljs-electron#1]
Just wanted to say this project was very helpful for getting me up and running. Any chance you could document a good route for packing this application for production.

**Comment by Gonzih** [comment]
Hi there, can you please clarify a bit more what would you like to see in those instructions? Are you interested in advanced compilation mode or just how to put everything in single binary? It's not really different from what you read in application distribution guide for electron, only thing that you just need to compile cljs beforehand.

**Comment by vincentjames501** [comment]
Yes. :advanced optimization, not relying on figwheel to be running to start the browser and other production flags that may be required. This is my first crack playing with electron so any help I could get the better. Also, when I checked this project out and ran it for the first time the images are not in the resources/public folder as it is .gitignored it looks like.

**Comment by Gonzih** [comment]
Ok, sure. I will try to write something on that in a couple of days. Feel free to poke me if that does not happen in a couple of weeks :)

**Comment by Gonzih** [comment]
Hi, so I reshuffled stuff around, switched all links to the local file system links. I did not try yet to package everything in to one electron binary, but so far compiled stuff works in release and dev modes. Please take a look at readme. I will continue improving everything related to the distribution soon.

**Comment by vincentjames501** [comment]
Haha I should've just done a pull request. You ended up with nearly exactly what I have. Thanks! Next step, a leiningen template ;)

**Comment by Gonzih** [comment]
:) I don't really like lein templates since it complicates testing and 
just playing around in my opinion.
But feel free to open issue or convert this project to it if you want.

Enjoy!
