### ISSUE TITLE
Advanced optimization

### ISSUE THREAD

**Issue by Engelberg** [Gonzih/cljs-electron#10]
Is there any way to use advanced optimization with electron?

**Comment by Gonzih** [comment]
Yeah, by creating custom externs file for electon apis I guess, I did not really try this.

**Comment by Gonzih** [comment]
I added initial support for externs inference in this branch https://github.com/Gonzih/cljs-electron/tree/infer-externs

**Comment by Gonzih** [comment]
Changes from this branch seem to be working great, merged in to master. Advanced compilation support is now in master.
