### ISSUE TITLE
Cider 

### ISSUE THREAD

**Issue by dclausen** [Gonzih/cljs-electron#13]
How would one connect a repl via cider?

**Comment by Gonzih** [comment]
I don't have experience with cider sadly, so I can't really answer this
question. Did you look at connecting cider to figwheel? This project uses
figwheel.

**Comment by Gonzih** [comment]
Please refer to the official figwheel documentation: https://github.com/bhauman/lein-figwheel/wiki/Using-the-Figwheel-REPL-within-NRepl#integration-with-emacscider

**Comment by lilactown** [comment]
@Gonzih I've added a few things (some scripts + dependencies) simply for quality of life when using nREPL + CIDER; would you accept a PR?

**Comment by Gonzih** [comment]
sure, if it does not break base functionality - go ahead.
