### ISSUE TITLE
Question: live-reloading electron-dev

### ISSUE THREAD

**Issue by philoskim** [Gonzih/cljs-electron#14]
Above all, thank you very much for this great info.

I know that this question is not appopriate here. 

I am so sorry about that but I have no choice but to write here.

My question is as follows.

Live-reloading frontend-dev works well by using figwheel but 
do you happen to know how to live-relaod electron-dev?

**Comment by Gonzih** [comment]
No, in this project electron-dev is not automatically reloded. But it should be possible to implent that. electron-dev runs inside nodejs process, and figwheel supports reload in nodejs. https://github.com/bhauman/lein-figwheel/wiki/Node.js-development-with-figwheel Only thing that you should watchout is start and stop of chromium and main electron browser window. I would suggest to use somenting like https://github.com/tolitius/mount for that purpose.

**Comment by philoskim** [comment]
Thanks for repid reply!

I searched the internet for the live-reloading in nodejs and my conclusions are as follows.

1) Only one instance of figwheel is available in one project. In other words, it is available only in nodejs or only in browser, not in both. In my opinion, if we use profile feature, the above problem may be avoidable. However the following obstacle is ahead of us.

2) figwheel requires that the optimization option should be :none, which is not fit for resources/main.js in electron-dev.

If I am wrong, please correct me!

**Comment by Gonzih** [comment]
1. I think figwheel nowadays can build mulitple compiler targets at the same time, It takes ids as a vector.
2. You are correct about :none optimization, but since it is node js anyway it should be able to load dependencies from multilple files, so :none should also work.
