### ISSUE TITLE
lean cooper command failing

### ISSUE THREAD

**Issue by oliverslade** [Gonzih/cljs-electron#15]
Hi,

I have cloned the repo,` ran npm install electron-prebuilt -g` but then when I run the `lein cooper` command i get the following stack trace: 
![image](https://user-images.githubusercontent.com/11063052/27002320-ccd64d48-4dd6-11e7-8222-86f054e59f54.png)

If I run: `lein trampoline cljsbuild auto electron-dev` and `lein trampoline figwheel frontend-dev` separately it works fine until I want to make any changes and re-run the application. It will then hang on Waiting for changes..

Apologies for my gap in knowledge. I am new to using clojure in this way.

**Comment by Gonzih** [comment]
It has nothing to do with the clojure itself. You dont have `env` command for some reason on your macos. Or it might be missing from your $PATH.
