### ISSUE TITLE
Compile warning on Hello World

### ISSUE THREAD

**Issue by sarahghp** [Gonzih/cljs-electron#16]
Hi there & thanks for this project! 

When I clone this repo and run the default example, then try to change text in `ui/core.cljs` (for instance, replace the "Electron" string, I get the following compiler error:

![screen shot 2017-08-06 at 1 57 25 pm](https://user-images.githubusercontent.com/1477362/29005724-786c2628-7aaf-11e7-9522-bdbf3bafc81e.png)

I don't need access to the file system just now, and once I comment out the `run-process` form and delete the the input where it is used, everything is fine, so it isn't a blocker for me or anything. Just wanted to let you know. 😃

**Comment by Gonzih** [comment]
That looks like something related to externs generation in cljs. Will try
to reproduce. Thanks for reporting this.

**Comment by NoNeedNoMore** [comment]
You can remove
`(set! *warn-on-infer* true)`
to avoid this issue, but I not sure that it is good solution.

**Comment by Gonzih** [comment]
I just removed *warn-on-infer*. Thanks for reporting this.
