### ISSUE TITLE
why is window background only white.

### ISSUE THREAD

**Issue by ssilb4** [Gonzih/cljs-electron#20]
I execute "lein cooper" and "electron ." and hello-world window appear. but It has only white content.

Although I changed root-component in ui/core.clj, It has only white background.
figwheel mark appear but It is same.

**Comment by ssilb4** [comment]
after "lein cooper"

message is 
21:51:23 ui       | Prompt will show when Figwheel connects to your application
21:51:24 ui       | May 20, 2019 9:51:24 PM org.jline.utils.Log logr
21:51:24 ui       | WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
21:51:24 ui       | Unable to detect a system Terminal, you must not launch the Rebel readline
21:51:24 ui       | from an intermediate process.
21:51:24 ui       | If you are using `lein` you may need to use `lein trampoline`.
21:51:24 ui       | Falling back to REPL without terminal readline functionality!
21:51:26 ui       | ClojureScript 1.10.238

**Comment by Gonzih** [comment]
Can you open a debug panel and take a look at Console tab to see if there are any javascript errors?

**Comment by oscarftoro** [comment]
core.cljs:13 Uncaught ReferenceError: require is not defined at core.cljs:13

that is in deed ui_core.cljs

**Comment by Gonzih** [comment]
Do you have `lein cooper` running in the background when you run `electron .`? Do you run `electron .` after you see figwheel startup message?

Try waiting for those messages in `lein cooper` output before running electron

```
15:14:22 ui       | Launching ClojureScript REPL for build: frontend-dev
15:14:22 ui       | Figwheel Controls:
15:14:22 ui       |           (stop-autobuild)                ;; stops Figwheel autobuilder
15:14:22 ui       |           (start-autobuild id ...)        ;; starts autobuilder focused on optional ids
15:14:22 ui       |           (switch-to-build id ...)        ;; switches autobuilder to different build
15:14:22 ui       |           (reset-autobuild)               ;; stops, cleans, and starts autobuilder
15:14:22 ui       |           (reload-config)                 ;; reloads build config and resets autobuild
15:14:22 ui       |           (build-once id ...)             ;; builds source one time
15:14:22 ui       |           (clean-builds id ..)            ;; deletes compiled cljs target files
15:14:22 ui       |           (print-config id ...)           ;; prints out build configurations
15:14:22 ui       |           (fig-status)                    ;; displays current state of system
15:14:22 ui       |           (figwheel.client/set-autoload false)    ;; will turn autoloading off
15:14:22 ui       |           (figwheel.client/set-repl-pprint false) ;; will turn pretty printing off
15:14:22 ui       |   Switch REPL build focus:
15:14:22 ui       |           :cljs/quit                      ;; allows you to switch REPL to another build
15:14:22 ui       |     Docs: (doc function-name-here)
15:14:22 ui       |     Exit: :cljs/quit
15:14:22 ui       |  Results: Stored in vars *1, *2, *3, *e holds last exception object
```

**Comment by ssilb4** [comment]
after "lein cooper"

20:44:47 ui       | Figwheel: Validating the configuration found in project.clj
20:44:47 ui       | Figwheel: Configuration Valid ;)
20:44:48 ui       | Figwheel: Starting server at http://0.0.0.0:3449
20:44:48 ui       | Figwheel: Watching build - frontend-dev
20:44:48 ui       | Compiling build :frontend-dev to "resources/public/js/ui-core.js" from ["ui_src" "dev_src"]...
20:44:49 ui       | Successfully compiled build :frontend-dev to "resources/public/js/ui-core.js" in 0.324 seconds.
20:44:49 ui       | Figwheel: Starting CSS Watcher for paths  ["resources/public/css"]
20:44:49 ui       | Launching ClojureScript REPL for build: frontend-dev
20:44:49 ui       | Figwheel Controls:
20:44:49 ui       |           (stop-autobuild)                ;; stops Figwheel autobuilder
20:44:49 ui       |           (start-autobuild id ...)        ;; starts autobuilder focused on optional ids
20:44:49 ui       |           (switch-to-build id ...)        ;; switches autobuilder to different build
20:44:49 ui       |           (reset-autobuild)               ;; stops, cleans, and starts autobuilder
20:44:49 ui       |           (reload-config)                 ;; reloads build config and resets autobuild
20:44:49 ui       |           (build-once id ...)             ;; builds source one time
20:44:49 ui       |           (clean-builds id ..)            ;; deletes compiled cljs target files
20:44:49 ui       |           (print-config id ...)           ;; prints out build configurations
20:44:49 ui       |           (fig-status)                    ;; displays current state of system
20:44:49 ui       |           (figwheel.client/set-autoload false)    ;; will turn autoloading off
20:44:49 ui       |           (figwheel.client/set-repl-pprint false) ;; will turn pretty printing off
20:44:49 ui       |   Switch REPL build focus:
20:44:49 ui       |           :cljs/quit                      ;; allows you to switch REPL to another build
20:44:49 ui       |     Docs: (doc function-name-here)
20:44:49 ui       |     Exit: :cljs/quit
20:44:49 ui       |  Results: Stored in vars *1, *2, *3, *e holds last exception object
20:44:49 ui       | Prompt will show when Figwheel connects to your application
20:44:50 ui       | May 29, 2019 8:44:50 PM org.jline.utils.Log logr
20:44:50 ui       | WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
20:44:50 ui       | Unable to detect a system Terminal, you must not launch the Rebel readline
20:44:50 ui       | from an intermediate process.
20:44:50 ui       | If you are using `lein` you may need to use `lein trampoline`.
20:44:50 ui       | Falling back to REPL without terminal readline functionality!
20:46:02 ui       | ClojureScript 1.10.238

and after I type "electron ." in another terminal, no change.

**Comment by Gonzih** [comment]
This is weird. I did try to run this on clean machine and everything seems
to be working. Could you provide details about your setup? OS, version of
electron you are running etc.

**Comment by ssilb4** [comment]
OS is ubuntu 18.04
electron is 5.0.1

what do I provide else?

**Comment by oscarftoro** [comment]
that is interesting: my OS is ubuntu 16.04 and electron 5.0.1  and I experience the same error.
I think it can be related to the Electron's version. 
https://stackoverflow.com/questions/44391448/electron-require-is-not-defined

**Comment by Gonzih** [comment]
I pushed a change that might fix this issue, i dont have atm a machine that i can test electron that is not in arch linux or nixos repositories (5+ is only available from npm).

Please if you have time take a pull changes from this repos master and give it a try.

**Comment by ssilb4** [comment]
thank you. it works well.

**Comment by Gonzih** [comment]
Glad to hear that it works, closing the issue.

Fixed!
