### ISSUE TITLE
[newbie] how to start this template ?

### ISSUE THREAD

**Issue by yellowbean** [Gonzih/cljs-electron#21]
I downloaded whole repo into my local, then install electron via `npm install electron -g`.
after that , I did "lein deps" in the right folder, then I try `lein cooper`
but terminal shows error
 "
![image](https://user-images.githubusercontent.com/1008321/62617950-a42ff880-b945-11e9-87fc-28659916e6bb.png)
"
any configuration I should do before running `lein cooper`?

my env: windows 10 ,

**Comment by Gonzih** [comment]
Huh, havent tried to run this on windows, but lets see if we can make this work.

Could you try to replace content of `Procfile` with this:

```
electron: lein trampoline cljsbuild auto electron-dev
ui: lein trampoline figwheel frontend-dev
```

And try running `lein cooper` again?

**Comment by yellowbean** [comment]
it turns out to be a bug from lein-cooper 

https://github.com/kouphax/lein-cooper/issues/11

if you  rename `lein` to `lein.bat` it fix this error message .
