### ISSUE TITLE
Live Changes not appearing live in Electron 

### ISSUE THREAD

**Issue by DavidYKay** [Gonzih/cljs-electron#3]
Hey there!

Great project. Very easy to get up and running.

One issue I'm having: Figwheel doesn't appear to be working correctly.

After saving my code, I wait a few seconds and then see the CLJS logo appear in the bottom-left corner, but the UI doesn't change. I need to hard-refresh in order to see my changes appear in the UI.

Any tips in chasing this one down?

Many thanks!

**Comment by DavidYKay** [comment]
Not sure what the issue was, but after restarting Electron, it's working now! Closing this.

Thanks again!

**Comment by Gonzih** [comment]
You are welcome :)
