### ISSUE TITLE
How to create a simpler template

### ISSUE THREAD

**Issue by abhi18av** [Gonzih/cljs-electron#6]
Hi @Gonzih , have another question regarding the template.

Clearly this is a production level template - what  I really want to know is to create a bare-essential template. I've tried experimenting with the various configurations but I can't get past the `dev.core` hurdle.

Could you, please help me create a much simpler template, for practice.

Thanks, looking forward to the response.

**Comment by Gonzih** [comment]
I'm sorry but I don't understand what you mean. This is very minimalistic template, only thing that makes it "production level" is fact that it allows you to do advanced optimization mode compilations.

**Comment by abhi18av** [comment]
Actually, I meant that f. ex. a simple Electron requires three files 
- index.html
- main.js
- package.json 

But here we've got a lot more ( necessary, agreed ) stuff but how can I go about simplifying the file structure. Say, just one `src` folder - so something along those lines.

**Comment by Gonzih** [comment]
You can replace dev_src folder with just main.js file in javascript. That's fine. Idea of this template is to show that everything can be done with clojurescript. This is complete working exapmle that should also be used for learning purpose. I don't see any issue with a project, so i will close this issue for now.
