### ISSUE TITLE
foreman error

### ISSUE THREAD

**Issue by Max-Tweddell** [Gonzih/cljs-electron#7]
While starting on a brand new project, the foreman ui process fails to work correctly.
This happens with any project name.
The version of Java is openjdk version 1.8.0_111.

> ➜  darude git:(master) foreman start
> 13:19:23 electron.1 | started with pid 6273
> 13:19:23 ui.1       | started with pid 6274
> 13:19:33 ui.1       | Figwheel: Starting server at http://localhost:3449
> 13:19:33 ui.1       | Figwheel: Watching build - frontend-dev
> 13:19:33 ui.1       | Compiling "resources/public/js/ui-core.js" from ["ui_src" "dev_src"]...
> 13:19:34 ui.1       | Successfully compiled "resources/public/js/ui-core.js" in 0.836 seconds.
> 13:19:34 ui.1       | clojure.lang.ExceptionInfo: Error in component :figwheel-system in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :figwheel-system, :component #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x447d14a9 {:status :ready, :val #<SystemMap>}]}, :system #<SystemMap>}
> 13:19:34 ui.1       |     at clojure.core$ex_info.invokeStatic(core.clj:4617)
> 13:19:34 ui.1       |     at clojure.core$ex_info.invoke(core.clj:4617)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invoke(component.cljc:116)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system$fn__16511.invoke(component.cljc:139)
> 13:19:34 ui.1       |     at clojure.lang.ArraySeq.reduce(ArraySeq.java:109)
> 13:19:34 ui.1       |     at clojure.core$reduce.invokeStatic(core.clj:6544)
> 13:19:34 ui.1       |     at clojure.core$reduce.invoke(core.clj:6527)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
> 13:19:34 ui.1       |     at clojure.lang.RestFn.invoke(RestFn.java:445)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component.SystemMap.start(component.cljc:178)
> 13:19:34 ui.1       |     at figwheel_sidecar.system$start_figwheel_BANG_.invokeStatic(system.clj:588)
> 13:19:34 ui.1       |     at figwheel_sidecar.system$start_figwheel_BANG_.invoke(system.clj:585)
> 13:19:34 ui.1       |     at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:137)
> 13:19:34 ui.1       |     at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:136)
> 13:19:34 ui.1       |     at user$eval18236.invokeStatic(3a21556c5edadad4510d86eef7e49e6a47c707f3-init.clj:1)
> 13:19:34 ui.1       |     at user$eval18236.invoke(3a21556c5edadad4510d86eef7e49e6a47c707f3-init.clj:1)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.eval(Compiler.java:6927)➜  darude git:(master) foreman start
> 13:19:23 electron.1 | started with pid 6273
> 13:19:23 ui.1       | started with pid 6274
> 13:19:33 ui.1       | Figwheel: Starting server at http://localhost:3449
> 13:19:33 ui.1       | Figwheel: Watching build - frontend-dev
> 13:19:33 ui.1       | Compiling "resources/public/js/ui-core.js" from ["ui_src" "dev_src"]...
> 13:19:34 ui.1       | Successfully compiled "resources/public/js/ui-core.js" in 0.836 seconds.
> 13:19:34 ui.1       | clojure.lang.ExceptionInfo: Error in component :figwheel-system in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key :figwheel-system, :component #figwheel_sidecar.system.FigwheelSystem{:system #object[clojure.lang.Atom 0x447d14a9 {:status :ready, :val #<SystemMap>}]}, :system #<SystemMap>}
> 13:19:34 ui.1       |     at clojure.core$ex_info.invokeStatic(core.clj:4617)
> 13:19:34 ui.1       |     at clojure.core$ex_info.invoke(core.clj:4617)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invoke(component.cljc:116)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system$fn__16511.invoke(component.cljc:139)
> 13:19:34 ui.1       |     at clojure.lang.ArraySeq.reduce(ArraySeq.java:109)
> 13:19:34 ui.1       |     at clojure.core$reduce.invokeStatic(core.clj:6544)
> 13:19:34 ui.1       |     at clojure.core$reduce.invoke(core.clj:6527)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
> 13:19:34 ui.1       |     at clojure.lang.RestFn.invoke(RestFn.java:445)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component.SystemMap.start(component.cljc:178)
> 13:19:34 ui.1       |     at figwheel_sidecar.system$start_figwheel_BANG_.invokeStatic(system.clj:588)
> 13:19:34 ui.1       |     at figwheel_sidecar.system$start_figwheel_BANG_.invoke(system.clj:585)
> 13:19:34 ui.1       |     at figwheel_sidecar.repl_api$start_figwheel_from_lein.invokeStatic(repl_api.clj:137)
> 13:19:34 ui.1       |     at figwheel_sidecar.repl_api$start_figwheel_from_lein.invoke(repl_api.clj:136)
> 13:19:34 ui.1       |     at user$eval18236.invokeStatic(3a21556c5edadad4510d86eef7e49e6a47c707f3-init.clj:1)
> 13:19:34 ui.1       |     at user$eval18236.invoke(3a21556c5edadad4510d86eef7e49e6a47c707f3-init.clj:1)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.eval(Compiler.java:6927)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.eval(Compiler.java:6917)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.load(Compiler.java:7379)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.loadFile(Compiler.java:7317)
> 13:19:34 ui.1       |     at clojure.main$load_script.invokeStatic(main.clj:275)
> 13:19:34 ui.1       |     at clojure.main$init_opt.invokeStatic(main.clj:277)
> 13:19:34 ui.1       |     at clojure.main$init_opt.invoke(main.clj:277)
> 13:19:34 ui.1       |     at clojure.main$initialize.invokeStatic(main.clj:308)
> 13:19:34 ui.1       |     at clojure.main$null_opt.invokeStatic(main.clj:342)
> 13:19:34 ui.1       |     at clojure.main$null_opt.invoke(main.clj:339)
> 13:19:34 ui.1       |     at clojure.main$main.invokeStatic(main.clj:421)
> 13:19:34 ui.1       |     at clojure.main$main.doInvoke(main.clj:384)
> 13:19:34 ui.1       |     at clojure.lang.RestFn.invoke(RestFn.java:421)
> 13:19:34 ui.1       |     at clojure.lang.Var.invoke(Var.java:383)
> 13:19:34 ui.1       |     at clojure.lang.AFn.applyToHelper(AFn.java:156)
> 13:19:34 ui.1       |     at clojure.lang.Var.applyTo(Var.java:700)
> 13:19:34 ui.1       |     at clojure.main.main(main.java:37)
> 13:19:34 ui.1       | Caused by: clojure.lang.ExceptionInfo: Error in component autobuild-frontend-dev in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key "autobuild-frontend-dev", :component #figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild{:build-config {:source-paths ["ui_src" "dev_src"], :id "frontend-dev", :build-options {:output-to "resources/public/js/ui-core.js", :output-dir "resources/public/js/ui-out", :source-map true, :asset-path "js/ui-out", :optimizations :none, :cache-analysis true, :main "dev.core"}, :compiler-env #object[clojure.lang.Atom 0x7ba9104f {:status :ready, :val #CompilerEnv{}}]}, :figwheel-server #figwheel_sidecar.components.figwheel_server.FigwheelServer{:connection-count #object[clojure.lang.Atom 0x617b1e76 {:status :ready, :val {}}], :browser-callbacks #object[clojure.lang.Atom 0x4d0f96ac {:status :ready, :val {}}], :ring-handler tools.figwheel-middleware/app, :file-change-atom #object[clojure.lang.Atom 0x4f880f30 {:status :ready, :val ()}], :compile-wait-time 10, :builds {"electron-dev" {:source-paths ["electron_src"], :id "electron-dev", :build-options {:output-to "resources/main.js", :optimizations :simple, :pretty-print true, :cache-analysis true, :output-dir "resources/out"}, :compiler-env #object[clojure.lang.Atom 0x7c9055e6 {:status :ready, :val #CompilerEnv{}}]}, "frontend-dev" {:source-paths ["ui_src" "dev_src"], :id "frontend-dev", :build-options {:output-to "resources/public/js/ui-core.js", :output-dir "resources/public/js/ui-out", :source-map true, :asset-path "js/ui-out", :optimizations :none, :cache-analysis true, :main "dev.core"}, :compiler-env #object[clojure.lang.Atom 0x7ba9104f {:status :ready, :val #CompilerEnv{}}]}, "electron-release" {:source-paths ["electron_src"], :id "electron-release", :build-options {:output-to "resources/main.js", :optimizations :simple, :pretty-print true, :cache-analysis true, :output-dir "resources/out"}, :compiler-env #object[clojure.lang.Atom 0x45a16cac {:status :ready, :val #CompilerEnv{}}]}, "frontend-release" {:source-paths ["ui_src"], :id "frontend-release", :build-options {:output-to "resources/public/js/ui-core.js", :output-dir "resources/public/js/ui-release-out", :source-map "resources/public/js/ui-core.js.map", :optimizations :simple, :cache-analysis true, :main "ui.core"}, :compiler-env #object[clojure.lang.Atom 0x74aa2842 {:status :ready, :val #CompilerEnv{}}]}}, :server-port 3449, :resolved-ring-handler #'tools.figwheel-middleware/app, :server-ip nil, :cljs-build-fn #object[figwheel_sidecar.components.cljs_autobuild$eval17988$figwheel_start_and_end_messages__17991$fn__17993 0x5951d91 "figwheel_sidecar.components.cljs_autobuild$eval17988$figwheel_start_and_end_messages__17991$fn__17993@5951d91"], :http-server #object[clojure.lang.AFunction$1 0x371c8e30 "clojure.lang.AFunction$1@371c8e30"], :open-file-command nil, :unique-id "/home/mtweddell/MEGA/MEGAsync/2016/Computer Science/ComputerScienceIA/darude", :log-writer #object[java.io.BufferedWriter 0x1ac864d7 "java.io.BufferedWriter@1ac864d7"], :file-md5-atom #object[clojure.lang.Atom 0x2fce09c0 {:status :ready, :val {}}], :http-server-root "public"}}, :system #<SystemMap>}
> 13:19:34 ui.1       |     at clojure.core$ex_info.invokeStatic(core.clj:4617)
> 13:19:34 ui.1       |     at clojure.core$ex_info.invoke(core.clj:4617)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invoke(component.cljc:116)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system$fn__16511.invoke(component.cljc:139)
> 13:19:34 ui.1       |     at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
> 13:19:34 ui.1       |     at clojure.core$reduce.invokeStatic(core.clj:6544)
> 13:19:34 ui.1       |     at clojure.core$reduce.invoke(core.clj:6527)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
> 13:19:34 ui.1       |     at clojure.lang.RestFn.invoke(RestFn.java:445)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component.SystemMap.start(component.cljc:178)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16442__16455.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16441__16458.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at clojure.lang.Atom.swap(Atom.java:37)
> 13:19:34 ui.1       |     at clojure.core$swap_BANG_.invokeStatic(core.clj:2260)
> 13:19:34 ui.1       |     at clojure.core$swap_BANG_.invoke(core.clj:2253)
> 13:19:34 ui.1       |     at figwheel_sidecar.system.FigwheelSystem.start(system.clj:119)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16442__16455.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16441__16458.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at clojure.lang.Var.invoke(Var.java:379)
> 13:19:34 ui.1       |     at clojure.lang.AFn.applyToHelper(AFn.java:154)
> 13:19:34 ui.1       |     at clojure.lang.Var.applyTo(Var.java:700)
> 13:19:34 ui.1       |     at clojure.core$apply.invokeStatic(core.clj:648)
> 13:19:34 ui.1       |     at clojure.core$apply.invoke(core.clj:641)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
> 13:19:34 ui.1       |     ... 36 more
> 13:19:34 ui.1       | Caused by: java.io.IOException: User limit of inotify watches reached
> 13:19:34 ui.1       |     at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
> 13:19:34 ui.1       |     at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
> 13:19:34 ui.1       |     at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
> 13:19:34 ui.1       |     at java.lang.Thread.run(Thread.java:745)
> 13:19:35 ui.1       | exited with code 1
> 13:19:35 system     | sending SIGTERM to all processes
> 13:19:35 electron.1 | exited with code 143
> 
> 13:19:34 ui.1       |     at clojure.lang.Compiler.eval(Compiler.java:6917)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.load(Compiler.java:7379)
> 13:19:34 ui.1       |     at clojure.lang.Compiler.loadFile(Compiler.java:7317)
> 13:19:34 ui.1       |     at clojure.main$load_script.invokeStatic(main.clj:275)
> 13:19:34 ui.1       |     at clojure.main$init_opt.invokeStatic(main.clj:277)
> 13:19:34 ui.1       |     at clojure.main$init_opt.invoke(main.clj:277)
> 13:19:34 ui.1       |     at clojure.main$initialize.invokeStatic(main.clj:308)
> 13:19:34 ui.1       |     at clojure.main$null_opt.invokeStatic(main.clj:342)
> 13:19:34 ui.1       |     at clojure.main$null_opt.invoke(main.clj:339)
> 13:19:34 ui.1       |     at clojure.main$main.invokeStatic(main.clj:421)
> 13:19:34 ui.1       |     at clojure.main$main.doInvoke(main.clj:384)
> 13:19:34 ui.1       |     at clojure.lang.RestFn.invoke(RestFn.java:421)
> 13:19:34 ui.1       |     at clojure.lang.Var.invoke(Var.java:383)
> 13:19:34 ui.1       |     at clojure.lang.AFn.applyToHelper(AFn.java:156)
> 13:19:34 ui.1       |     at clojure.lang.Var.applyTo(Var.java:700)
> 13:19:34 ui.1       |     at clojure.main.main(main.java:37)
> 13:19:34 ui.1       | Caused by: clojure.lang.ExceptionInfo: Error in component autobuild-frontend-dev in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start {:reason :com.stuartsierra.component/component-function-threw-exception, :function #'com.stuartsierra.component/start, :system-key "autobuild-frontend-dev", :component #figwheel_sidecar.components.cljs_autobuild.CLJSAutobuild{:build-config {:source-paths ["ui_src" "dev_src"], :id "frontend-dev", :build-options {:output-to "resources/public/js/ui-core.js", :output-dir "resources/public/js/ui-out", :source-map true, :asset-path "js/ui-out", :optimizations :none, :cache-analysis true, :main "dev.core"}, :compiler-env #object[clojure.lang.Atom 0x7ba9104f {:status :ready, :val #CompilerEnv{}}]}, :figwheel-server #figwheel_sidecar.components.figwheel_server.FigwheelServer{:connection-count #object[clojure.lang.Atom 0x617b1e76 {:status :ready, :val {}}], :browser-callbacks #object[clojure.lang.Atom 0x4d0f96ac {:status :ready, :val {}}], :ring-handler tools.figwheel-middleware/app, :file-change-atom #object[clojure.lang.Atom 0x4f880f30 {:status :ready, :val ()}], :compile-wait-time 10, :builds {"electron-dev" {:source-paths ["electron_src"], :id "electron-dev", :build-options {:output-to "resources/main.js", :optimizations :simple, :pretty-print true, :cache-analysis true, :output-dir "resources/out"}, :compiler-env #object[clojure.lang.Atom 0x7c9055e6 {:status :ready, :val #CompilerEnv{}}]}, "frontend-dev" {:source-paths ["ui_src" "dev_src"], :id "frontend-dev", :build-options {:output-to "resources/public/js/ui-core.js", :output-dir "resources/public/js/ui-out", :source-map true, :asset-path "js/ui-out", :optimizations :none, :cache-analysis true, :main "dev.core"}, :compiler-env #object[clojure.lang.Atom 0x7ba9104f {:status :ready, :val #CompilerEnv{}}]}, "electron-release" {:source-paths ["electron_src"], :id "electron-release", :build-options {:output-to "resources/main.js", :optimizations :simple, :pretty-print true, :cache-analysis true, :output-dir "resources/out"}, :compiler-env #object[clojure.lang.Atom 0x45a16cac {:status :ready, :val #CompilerEnv{}}]}, "frontend-release" {:source-paths ["ui_src"], :id "frontend-release", :build-options {:output-to "resources/public/js/ui-core.js", :output-dir "resources/public/js/ui-release-out", :source-map "resources/public/js/ui-core.js.map", :optimizations :simple, :cache-analysis true, :main "ui.core"}, :compiler-env #object[clojure.lang.Atom 0x74aa2842 {:status :ready, :val #CompilerEnv{}}]}}, :server-port 3449, :resolved-ring-handler #'tools.figwheel-middleware/app, :server-ip nil, :cljs-build-fn #object[figwheel_sidecar.components.cljs_autobuild$eval17988$figwheel_start_and_end_messages__17991$fn__17993 0x5951d91 "figwheel_sidecar.components.cljs_autobuild$eval17988$figwheel_start_and_end_messages__17991$fn__17993@5951d91"], :http-server #object[clojure.lang.AFunction$1 0x371c8e30 "clojure.lang.AFunction$1@371c8e30"], :open-file-command nil, :unique-id "/home/mtweddell/MEGA/MEGAsync/2016/Computer Science/ComputerScienceIA/darude", :log-writer #object[java.io.BufferedWriter 0x1ac864d7 "java.io.BufferedWriter@1ac864d7"], :file-md5-atom #object[clojure.lang.Atom 0x2fce09c0 {:status :ready, :val {}}], :http-server-root "public"}}, :system #<SystemMap>}
> 13:19:34 ui.1       |     at clojure.core$ex_info.invokeStatic(core.clj:4617)
> 13:19:34 ui.1       |     at clojure.core$ex_info.invoke(core.clj:4617)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invokeStatic(component.cljc:119)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invoke(component.cljc:116)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system$fn__16511.invoke(component.cljc:139)
> 13:19:34 ui.1       |     at clojure.lang.ArraySeq.reduce(ArraySeq.java:114)
> 13:19:34 ui.1       |     at clojure.core$reduce.invokeStatic(core.clj:6544)
> 13:19:34 ui.1       |     at clojure.core$reduce.invoke(core.clj:6527)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.invokeStatic(component.cljc:135)
> 13:19:34 ui.1       |     at com.stuartsierra.component$update_system.doInvoke(component.cljc:129)
> 13:19:34 ui.1       |     at clojure.lang.RestFn.invoke(RestFn.java:445)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:163)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invokeStatic(component.cljc:161)
> 13:19:34 ui.1       |     at com.stuartsierra.component$start_system.invoke(component.cljc:155)
> 13:19:34 ui.1       |     at com.stuartsierra.component.SystemMap.start(component.cljc:178)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16442__16455.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16441__16458.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at clojure.lang.Atom.swap(Atom.java:37)
> 13:19:34 ui.1       |     at clojure.core$swap_BANG_.invokeStatic(core.clj:2260)
> 13:19:34 ui.1       |     at clojure.core$swap_BANG_.invoke(core.clj:2253)
> 13:19:34 ui.1       |     at figwheel_sidecar.system.FigwheelSystem.start(system.clj:119)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16442__16455.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at com.stuartsierra.component$eval16452$fn__16453$G__16441__16458.invoke(component.cljc:5)
> 13:19:34 ui.1       |     at clojure.lang.Var.invoke(Var.java:379)
> 13:19:34 ui.1       |     at clojure.lang.AFn.applyToHelper(AFn.java:154)
> 13:19:34 ui.1       |     at clojure.lang.Var.applyTo(Var.java:700)
> 13:19:34 ui.1       |     at clojure.core$apply.invokeStatic(core.clj:648)
> 13:19:34 ui.1       |     at clojure.core$apply.invoke(core.clj:641)
> 13:19:34 ui.1       |     at com.stuartsierra.component$try_action.invokeStatic(component.cljc:117)
> 13:19:34 ui.1       |     ... 36 more
> 13:19:34 ui.1       | Caused by: java.io.IOException: User limit of inotify watches reached
> 13:19:34 ui.1       |     at sun.nio.fs.LinuxWatchService$Poller.implRegister(LinuxWatchService.java:264)
> 13:19:34 ui.1       |     at sun.nio.fs.AbstractPoller.processRequests(AbstractPoller.java:260)
> 13:19:34 ui.1       |     at sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:329)
> 13:19:34 ui.1       |     at java.lang.Thread.run(Thread.java:745)
> 13:19:35 ui.1       | exited with code 1
> 13:19:35 system     | sending SIGTERM to all processes
> 13:19:35 electron.1 | exited with code 143

**Comment by Gonzih** [comment]
> User limit of inotify watches reached

this is main problem as far as I can tell. You need to increase this limit.

Please take a look at: http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached

Tell me if that helps.
