### ISSUE TITLE
*advice* electron api unclear interop

### ISSUE THREAD

**Issue by lazylazylazy** [Gonzih/cljs-electron#8]
Really enjoying this project as a way of introducing myself to cljs and electron. 

However it's a bit unclear how the electron.core calls the electron api in the renderer process.  For example how would we be able to utilise the web-frame options or create menu objects? 

Defining .-web-frame in the same way as .-BrowserWindow causes a compile error in the foreman task.

**Comment by Gonzih** [comment]
Can you please provide a javascript snippet of what you are trying to achive?

**Comment by lazylazylazy** [comment]
javascript From Electron docs -
const {webFrame} = require('electron')
webFrame.setZoomLevelLimits(1, 1)

However (def web-frame (.-web-frame electron)) creates a null pointer in main.js

Thanks

clarity - it is referred to as web-frame in many examples rather than webFrame, which creates the same problem anyway

**Comment by lazylazylazy** [comment]
clarity - it is referred to as web-frame in many examples rather than webFrame

**Comment by Gonzih** [comment]
What about `(def web-frame (.-webFrame electron))`?

**Comment by lazylazylazy** [comment]
yes, thank you, that sorted that. But now "web-frame is not a constructor" and set isn't made.

**Comment by Gonzih** [comment]
Please show your clojurescript code.

**Comment by lazylazylazy** [comment]
(.on @main-window "ready-to-show" #(set! (.-setZoomLevelLimits web-frame) (1, 1)))

also tried as a map but that kicked up a fuss on loading electron, not at compile.

many thanks!

**Comment by Gonzih** [comment]
`setZoomLevelLimits` is a function, not a property. `set!` mutates property, so you are doing couple of things wrong. You are mutating property that is function and then you are calling `1` as a function giving it`1` as an argument.

Your code should look something like this:

```clojure
(.on @main-window "ready-to-show" #(.setZoomLevelLimits web-frame 1 1))
```

**Comment by lazylazylazy** [comment]
Thanks for your help with this.
Total misunderstanding on my part - this needs to be called in the ui.core, not in the electron process.
Sorry for polluting your issues.

**Comment by Gonzih** [comment]
Glad to hear that you figured this out! Closing the issue.
